apiVersion: v1
kind: Service
metadata:
  name: willapp-service
  namespace: dev
spec:
  selector:
    app: willapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      # nodePort: 30088