apiVersion: v1

kind: Service

metadata:
  name: app1-service

spec:
  selector:
    app: app1
  # type: NodePort
  ports:
    - protocol: TCP
      # nodePort: 30001
      port: 80
      targetPort: 80

      # /usr/share/nginx/html