apiVersion: v1

kind: Service

metadata:
  name: app3-service

spec:
  selector:
    app: app3
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30002
      port: 30002
      targetPort: 80

      # /usr/share/nginx/html