apiVersion: apps/v1

kind: Deployment
metadata:
  name: willapp
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: willapp
  template:
    metadata:
      labels:
        app: willapp
    spec:
      containers:
        - name: willapp
          image: wil42/playground:v1
          ports:
            - containerPort: 8888
